---
- name: Add Wazuh GPG key
  become: yes
  ansible.builtin.apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present
    keyring: /usr/share/keyrings/wazuh.gpg

- name: Add Wazuh APT repo
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
    state: present
    filename: wazuh

- name: Install wazuh-agent
  become: yes
  ansible.builtin.apt: { name: wazuh-agent, state: present, update_cache: yes }

- name: Configure manager address
  become: yes
  ansible.builtin.replace:
    path: /var/ossec/etc/ossec.conf
    regexp: '<address>.*</address>'
    replace: '<address>{{ lookup("env", "WAZUH_MANAGER_LB_IP") | default("172.22.10.62") }}</address>'

- name: Ensure localfile for pfSense logs
  become: yes
  ansible.builtin.blockinfile:
    path: /var/ossec/etc/ossec.conf
    marker: "<!-- PF-SOC-9000 {mark} -->"
    block: |
      <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/pfsense/pfsense.log</location>
      </localfile>

- name: Enable & restart agent
  become: yes
  ansible.builtin.service: { name: wazuh-agent, state: restarted, enabled: yes }
