apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
  namespace: victim
spec:
  replicas: 1
  selector: { matchLabels: { app: dvwa } }
  template:
    metadata: { labels: { app: dvwa } }
    spec:
      containers:
        - name: dvwa
          image: vulnerables/web-dvwa:latest
          imagePullPolicy: IfNotPresent
          ports: [{containerPort: 80}]
          readinessProbe:
            httpGet: { path: /login.php, port: 80 }
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa
  namespace: victim
spec:
  type: ClusterIP
  selector: { app: dvwa }
  ports:
    - { name: http, port: 80, targetPort: 80 }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dvwa
  namespace: victim
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: dvwa.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: dvwa, port: { number: 80 } }
