---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy Wazuh into the 'soc' namespace
namespace: soc

# Upstream base (local clone path created by the deploy script)
resources:
  - ../../../third_party/wazuh-kubernetes/envs/local-env

# Add our ingress on top
patchesStrategicMerge:
  - ingress-dashboard.yaml

# Generate secrets from cert files produced by the deploy script
secretGenerator:
  - name: indexer-certs
    files:
      - certs/indexer_cluster/root-ca.pem
      - certs/indexer_cluster/node.pem
      - certs/indexer_cluster/node-key.pem
      - certs/indexer_cluster/dashboard.pem
      - certs/indexer_cluster/dashboard-key.pem
      - certs/indexer_cluster/admin.pem
      - certs/indexer_cluster/admin-key.pem
      - certs/indexer_cluster/filebeat.pem
      - certs/indexer_cluster/filebeat-key.pem
    options: { disableNameSuffixHash: true }

  - name: dashboard-certs
    files:
      - certs/dashboard_http/cert.pem
      - certs/dashboard_http/key.pem
      - certs/indexer_cluster/root-ca.pem
    options: { disableNameSuffixHash: true }
